export enum ContentTags {
  TECHNOLOGY = 'TECHNOLOGY',
  SPORTS = 'SPORTS',
  HEALTH = 'HEALTH',
  EDUCATION = 'EDUCATION',
  ENTERTAINMENT = 'ENTERTAINMENT',
  TRAVEL = 'TRAVEL',
  FOOD = 'FOOD',
  LIFESTYLE = 'LIFESTYLE',
  BUSINESS = 'BUSINESS',
  SCIENCE = 'SCIENCE',
}